/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ResourcesSchoolsRouteImport } from './routes/resources/schools'
import { Route as ResourcesSafetyRouteImport } from './routes/resources/safety'
import { Route as ResourcesParentsRouteImport } from './routes/resources/parents'
import { Route as ResourcesFaqRouteImport } from './routes/resources/faq'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSchoolsRoute = ResourcesSchoolsRouteImport.update({
  id: '/resources/schools',
  path: '/resources/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSafetyRoute = ResourcesSafetyRouteImport.update({
  id: '/resources/safety',
  path: '/resources/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesParentsRoute = ResourcesParentsRouteImport.update({
  id: '/resources/parents',
  path: '/resources/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFaqRoute = ResourcesFaqRouteImport.update({
  id: '/resources/faq',
  path: '/resources/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/parents': typeof ResourcesParentsRoute
  '/resources/safety': typeof ResourcesSafetyRoute
  '/resources/schools': typeof ResourcesSchoolsRoute
  '/about/': typeof AboutIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/parents': typeof ResourcesParentsRoute
  '/resources/safety': typeof ResourcesSafetyRoute
  '/resources/schools': typeof ResourcesSchoolsRoute
  '/about': typeof AboutIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/parents': typeof ResourcesParentsRoute
  '/resources/safety': typeof ResourcesSafetyRoute
  '/resources/schools': typeof ResourcesSchoolsRoute
  '/about/': typeof AboutIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/programs/$slug'
    | '/resources/faq'
    | '/resources/parents'
    | '/resources/safety'
    | '/resources/schools'
    | '/about/'
    | '/programs/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/programs/$slug'
    | '/resources/faq'
    | '/resources/parents'
    | '/resources/safety'
    | '/resources/schools'
    | '/about'
    | '/programs'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/programs/$slug'
    | '/resources/faq'
    | '/resources/parents'
    | '/resources/safety'
    | '/resources/schools'
    | '/about/'
    | '/programs/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ResourcesFaqRoute: typeof ResourcesFaqRoute
  ResourcesParentsRoute: typeof ResourcesParentsRoute
  ResourcesSafetyRoute: typeof ResourcesSafetyRoute
  ResourcesSchoolsRoute: typeof ResourcesSchoolsRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/schools': {
      id: '/resources/schools'
      path: '/resources/schools'
      fullPath: '/resources/schools'
      preLoaderRoute: typeof ResourcesSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/safety': {
      id: '/resources/safety'
      path: '/resources/safety'
      fullPath: '/resources/safety'
      preLoaderRoute: typeof ResourcesSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/parents': {
      id: '/resources/parents'
      path: '/resources/parents'
      fullPath: '/resources/parents'
      preLoaderRoute: typeof ResourcesParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/faq': {
      id: '/resources/faq'
      path: '/resources/faq'
      fullPath: '/resources/faq'
      preLoaderRoute: typeof ResourcesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ResourcesFaqRoute: ResourcesFaqRoute,
  ResourcesParentsRoute: ResourcesParentsRoute,
  ResourcesSafetyRoute: ResourcesSafetyRoute,
  ResourcesSchoolsRoute: ResourcesSchoolsRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
